[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#5c6370"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#ffffff"
yellow = "#d19a66"

[colors.normal]
black = "#282c34"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#abb2bf"
yellow = "#d19a66"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[font]
size = 12

[font.normal]
family = "Ubuntu Mono derivative Powerline"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[scrolling]
history = 10000

[window]
dynamic_title = true
opacity = 0.8

[keyboard]
